fieldLayouts:
  d01c9b33-b967-405c-b20e-0ccbb7f80cf7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 34b8b599-5cbb-4c63-bfeb-ca1ac4629214
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e68987c1-ae5a-48c5-a6f2-3031e10c903d # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76346ff6-fb54-473a-9bad-4080fb607d60
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3956f49-9876-4219-95f1-e50a5d448c4b # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f275909f-c462-453f-8ffd-bf3176dc927d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 412c2a47-6dff-4a39-9e08-229a5985df32
        userCondition: null
handle: contactPage
hasTitleField: true
name: 'Contact Page'
section: 032aa4a8-1625-42c8-917f-829236b14e41 # Contact Page
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
