fieldLayouts:
  c444c31a-7dd9-422b-9b3f-636f878417f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6b8f392-f836-4c0e-baa7-f8610c9186f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e68987c1-ae5a-48c5-a6f2-3031e10c903d # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac8ee750-4a12-4a6b-8b25-ee16ff097dda
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f3956f49-9876-4219-95f1-e50a5d448c4b # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb8b4523-8cec-427e-bec2-9cef4704b7fd
            userCondition: null
            warning: null
            width: 100
        name: 'Basic Information'
        uid: 59058dda-16f6-426d-8e68-81888e849c8c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f0998072-e809-4af9-82bd-c986990b6c1b # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcd2b04d-e61c-442f-bbec-c745face2141
            userCondition: null
            warning: null
            width: 100
        name: 'Detail Content'
        uid: 96e0670d-8c0c-4685-92cf-f695da5cfd77
        userCondition: null
handle: detail
hasTitleField: true
name: Detail
section: 00c9e121-423e-4977-b259-c5095c743040 # Cases
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
