fieldLayouts:
  53a22dc0-fd6a-4a69-bc1f-b7ce963ed1bb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c0ed1402-a1a4-4f66-823e-ad305f244e8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1575c6bf-cbc8-4bdb-b332-dbe102d25379
        userCondition: null
fs: uploads
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
