columnSuffix: null
contentColumnType: string
fieldGroup: 48278a33-f3ca-4301-afda-73d485b628a3 # Common
handle: categorySelector
instructions: null
name: 'Category Selector'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:4844a3cb-355c-4c1c-8f43-3e7cb1efe0ca' # Project Types
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
