columnSuffix: zvybxmvr
contentColumnType: text
fieldGroup: 48278a33-f3ca-4301-afda-73d485b628a3 # Common
handle: description
instructions: 'Use a rather short description.'
name: Description
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
