dateModified: 1670251582
email:
  fromEmail: adriaan@pgm.gent
  fromName: 'PGM Gent'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    00c9e121-423e-4977-b259-c5095c743040: Cases # Cases
    0ea98110-cff9-4d61-90a4-95aef918dbdf: 'Cases Page' # Cases Page
    1af38875-d936-4360-a5d0-437ef7ad6e24: 'PGM Ghent' # PGM Ghent
    3dde279e-f1f5-4b05-96b1-bdaae50a9719: 'Entry Selector' # Entry Selector
    6cdf173a-339c-4f65-b1cf-30a98d4baa98: 'Cases Page' # Cases Page
    7fbad75b-1d64-4ae6-8bf5-701ec1f995ea: 'PGM Gent' # PGM Gent
    9d6023f5-7886-4299-a756-b4d90961c904: 'PGM Gent' # PGM Gent
    79d175c7-268e-4d7a-b26e-c9f9c878f4a6: 'External Link' # External Link
    385d0aa9-4485-4a80-9c4c-26817c3482df: Navigation # Navigation
    48278a33-f3ca-4301-afda-73d485b628a3: Common # Common
    79541de8-894d-4788-b16f-a2692d8c35f0: 'Home Page' # Home Page
    85390e38-228d-4230-9d1d-f67dc15e3aed: Detail # Detail
    087704f8-ccc9-477c-9c2c-a56e8eb2c726: 'Internal Link' # Internal Link
    a1f2bc7e-94ac-410c-b80c-760f646cf23c: External # External
    b8af73e6-f8b7-4866-8b48-4cc5f749751d: Teachers # Teachers
    b253e70b-f1db-4d43-98d2-178e2d6d523f: 'Button Style Selector' # Button Style Selector
    d7b9dc9c-9659-4f7d-9c51-14765c4634f1: 'Cases Selector' # Cases Selector
    e68987c1-ae5a-48c5-a6f2-3031e10c903d: Description # Description
    ea678ff1-35d7-463e-b7e9-8f3123f83314: 'External Link' # External Link
    f2b7696c-a4bb-450f-bd2d-39b20fb1bb6b: 'Home Page' # Home Page
    fc541612-4c9d-4034-a75a-a9cb9df1899e: Admins # Admins
plugins:
  mix:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      assetPath: dist
      publicPath: web
system:
  edition: pro
  live: true
  name: 'PGM Gent'
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
