fieldLayouts:
  724dd7a6-aa77-4ba4-a1d8-a21b77d7c7c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f3956f49-9876-4219-95f1-e50a5d448c4b # Image
            instructions: 'Upload a logo, preferably a vector image.'
            label: Logo
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 323ebcc8-89d7-4c85-8ee5-8f50b6982f95
            userCondition: null
            warning: null
            width: 100
        name: Branding
        uid: d41bf42a-9ae3-40ad-82b5-da586bd3a857
        userCondition: null
handle: branding
name: Branding
sortOrder: 1
