defaultPlacement: end
enableVersioning: true
handle: navigation
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  1af38875-d936-4360-a5d0-437ef7ad6e24: # PGM Ghent
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  7fbad75b-1d64-4ae6-8bf5-701ec1f995ea: # PGM Gent
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 0a0ebe24-ad40-447d-be4d-4c5f7b5bdd7b
type: structure
